### ISSUE TITLE
Chase Macro places cards in two stacks in bottom right corner of scene

### ISSUE THREAD

**Issue by kristianserrano** [brunocalado/swademacros#1]
When I run the Chase macro, it places the cards into two stacks in the bottom left corner of the scene. It places one card, the places the remaining 8 to the right. On a smaller scene it stacks them all into one stack.

![Screen Shot 2021-06-05 at 3 26 40 PM](https://user-images.githubusercontent.com/1796189/120903147-6fa92880-c612-11eb-8166-c11a79d70e1c.png)

**Comment by brunocalado** [comment]
Hi. 

I tested here. 
![image](https://user-images.githubusercontent.com/4999783/120907695-0dfcb480-c63a-11eb-9fa2-4817fcf6b636.png)

1. Can you share the macro settings?
2. Can you use the macro from the update 0.0.8?
3. Can you share the scene settings?

**Comment by brunocalado** [comment]
Dogfight worked too...
![image](https://user-images.githubusercontent.com/4999783/120907743-53b97d00-c63a-11eb-9590-a54a1b26094f.png)

**Comment by kristianserrano** [comment]
Apparently, The Forge only sees 0.0.7, even when I try to install from the manifest URL which indicates 0.0.8.
https://raw.githubusercontent.com/brunocalado/swademacros/main/module.json

The scene itself is just a basic landing page. Nothing special about it.

Here's the current macro being used:
```js
const version = 'v1.1';

/* Chase
Features
- Draw n cards placing them in the scene
- This macro can reset the table preventing from the error
- This macro can line up the cards
source: 
icon: icons/sundries/gaming/playing-cards.webp
*/

main();

function main() {
  //How Many Cards to Draw
  //Width/Height
  //Which Table to Draw From
  let cardsList = "";
  Array.from(game.tables).map((el) => {
    cardsList += `<option value="${el.data.name}">${el.data.name}</option>`;
  });

  let template = `
  <p>Table to Draw From: <select id="tableName">${cardsList}</select></p>
  <p>
    Cards to Draw (Lines x Columns): <input id="dogFightLines" type="number" min="1" style="width: 50px;" value=1> x <input id="dogFightColumns" type="number" min="1" style="width: 50px;" value=9>
  </p>  
  <p>
    Height: <input id="height" type="number" min="1" style="width: 50px" value=150>
    Width: <input id="width" type="number" min="1" style="width: 50px" value=107>
  </p>
  <br />
  <p>
    <input type="checkbox" id="reset" checked/>
    Reset Table?
  </p> 
  <p>
    <input type="checkbox" id="stackupcards"/>
    Just stack up all cards
  </p>  
  <br />  
  <p>
    <h3>Horizontal spacing between cards</h3>
    <input id="spacingx" type="range" min="0" max="100" value="20" step="5">
  </p>
  <p>
    <h3>Vertical spacing between cards (dogfight only)</h3>
    <input id="spacingy" type="range" min="0" max="100" value="100" step="5">  
  </p>
  `;
  new Dialog({
    title: `Draw Cards To Table - ${version}`,
    content: template,
    buttons: {
      ok: {
        label: "Draw",
        callback: async (html) => {
          makeTiles(html);
        },
      },
      cancel: {
        label: "Cancel",
      },
    },
  }).render(true);
}

async function makeTiles(html) {  
  let spacingx = html.find("#spacingx")[0].value/100;
  let spacingy = html.find("#spacingy")[0].value/100;
  let dogFightLines = html.find("#dogFightLines")[0].value;
  let dogFightColumns = html.find("#dogFightColumns")[0].value;  
  let resetTable = html.find("#reset")[0].value;
  const stackupcards = html.find("#stackupcards")[0].checked;
  let tableName = html.find("#tableName")[0].value;
  let cardsToDraw = dogFightLines*dogFightColumns;
  let height = html.find("#height")[0].value;
  let width = html.find("#width")[0].value;

  if (resetTable=='on') {
    await game.tables.find((el) => el.data.name == tableName).reset();
  }

  let cardDraws = (
    await game.tables
      .find((el) => el.data.name == tableName)
      .drawMany(cardsToDraw)
  ).results;
/*
let cardDraws = ( await game.tables.find((el) => el.data.name == 'Action Cards').drawMany(5).results );
*/

  let centerX = Math.round(game.scenes.active.data.width/3);
  let centerY = Math.round(game.scenes.active.data.height/2);
  
  let deltaX = 0;
  let deltaY = 0;
  let counter = 0;
  
  //console.log(spacingx + '/' + spacingy + ' stackupcards:' + (stackupcards!='on'));
  let tData;
  for (let y = 0; y < dogFightLines; y++) {
    deltaY = Math.round( height*y + height*spacingy*y );
    for (let x = 0; x < dogFightColumns; x++) {                
      deltaX = Math.round( width*x + width*spacingx*x );            
      if (stackupcards) {
        deltaX = 0;
        deltaY = 0;        
      }
      tData = {
        img: cardDraws[counter].data.img,
        width: parseInt(width),
        height: parseInt(height),
        x: parseInt(centerX + deltaX),
        y: parseInt(centerY + deltaY)
      };
      console.log(tData);
      await TileDocument.create(tData, {parent: canvas.scene});      
      //console.log('x:' + x + ' y:' + y + ' counter:' + counter + ' deltaX:' + deltaX + ' deltaY:' + deltaY);
      counter = counter + 1;
      //console.log('centerX: ' + centerX + ' / deltaX: ' + deltaX + ' / centerX+deltaX:' + (centerX+deltaX) ); 
    }      
  }
}
```

**Comment by brunocalado** [comment]
It's the last one

> Apparently, The Forge only sees 0.0.7, even when I try to install from the manifest URL which indicates 0.0.8.
> https://raw.githubusercontent.com/brunocalado/swademacros/main/module.json
> 
> The scene itself is just a basic landing page. Nothing special about it.
> 
> Here's the current macro being used:
> 
> ```js
> const version = 'v1.1';
> 
> /* Chase
> Features
> - Draw n cards placing them in the scene
> - This macro can reset the table preventing from the error
> - This macro can line up the cards
> source: 
> icon: icons/sundries/gaming/playing-cards.webp
> */
> 
> main();
> 
> function main() {
>   //How Many Cards to Draw
>   //Width/Height
>   //Which Table to Draw From
>   let cardsList = "";
>   Array.from(game.tables).map((el) => {
>     cardsList += `<option value="${el.data.name}">${el.data.name}</option>`;
>   });
> 
>   let template = `
>   <p>Table to Draw From: <select id="tableName">${cardsList}</select></p>
>   <p>
>     Cards to Draw (Lines x Columns): <input id="dogFightLines" type="number" min="1" style="width: 50px;" value=1> x <input id="dogFightColumns" type="number" min="1" style="width: 50px;" value=9>
>   </p>  
>   <p>
>     Height: <input id="height" type="number" min="1" style="width: 50px" value=150>
>     Width: <input id="width" type="number" min="1" style="width: 50px" value=107>
>   </p>
>   <br />
>   <p>
>     <input type="checkbox" id="reset" checked/>
>     Reset Table?
>   </p> 
>   <p>
>     <input type="checkbox" id="stackupcards"/>
>     Just stack up all cards
>   </p>  
>   <br />  
>   <p>
>     <h3>Horizontal spacing between cards</h3>
>     <input id="spacingx" type="range" min="0" max="100" value="20" step="5">
>   </p>
>   <p>
>     <h3>Vertical spacing between cards (dogfight only)</h3>
>     <input id="spacingy" type="range" min="0" max="100" value="100" step="5">  
>   </p>
>   `;
>   new Dialog({
>     title: `Draw Cards To Table - ${version}`,
>     content: template,
>     buttons: {
>       ok: {
>         label: "Draw",
>         callback: async (html) => {
>           makeTiles(html);
>         },
>       },
>       cancel: {
>         label: "Cancel",
>       },
>     },
>   }).render(true);
> }
> 
> async function makeTiles(html) {  
>   let spacingx = html.find("#spacingx")[0].value/100;
>   let spacingy = html.find("#spacingy")[0].value/100;
>   let dogFightLines = html.find("#dogFightLines")[0].value;
>   let dogFightColumns = html.find("#dogFightColumns")[0].value;  
>   let resetTable = html.find("#reset")[0].value;
>   const stackupcards = html.find("#stackupcards")[0].checked;
>   let tableName = html.find("#tableName")[0].value;
>   let cardsToDraw = dogFightLines*dogFightColumns;
>   let height = html.find("#height")[0].value;
>   let width = html.find("#width")[0].value;
> 
>   if (resetTable=='on') {
>     await game.tables.find((el) => el.data.name == tableName).reset();
>   }
> 
>   let cardDraws = (
>     await game.tables
>       .find((el) => el.data.name == tableName)
>       .drawMany(cardsToDraw)
>   ).results;
> /*
> let cardDraws = ( await game.tables.find((el) => el.data.name == 'Action Cards').drawMany(5).results );
> */
> 
>   let centerX = Math.round(game.scenes.active.data.width/3);
>   let centerY = Math.round(game.scenes.active.data.height/2);
>   
>   let deltaX = 0;
>   let deltaY = 0;
>   let counter = 0;
>   
>   //console.log(spacingx + '/' + spacingy + ' stackupcards:' + (stackupcards!='on'));
>   let tData;
>   for (let y = 0; y < dogFightLines; y++) {
>     deltaY = Math.round( height*y + height*spacingy*y );
>     for (let x = 0; x < dogFightColumns; x++) {                
>       deltaX = Math.round( width*x + width*spacingx*x );            
>       if (stackupcards) {
>         deltaX = 0;
>         deltaY = 0;        
>       }
>       tData = {
>         img: cardDraws[counter].data.img,
>         width: parseInt(width),
>         height: parseInt(height),
>         x: parseInt(centerX + deltaX),
>         y: parseInt(centerY + deltaY)
>       };
>       console.log(tData);
>       await TileDocument.create(tData, {parent: canvas.scene});      
>       //console.log('x:' + x + ' y:' + y + ' counter:' + counter + ' deltaX:' + deltaX + ' deltaY:' + deltaY);
>       counter = counter + 1;
>       //console.log('centerX: ' + centerX + ' / deltaX: ' + deltaX + ' / centerX+deltaX:' + (centerX+deltaX) ); 
>     }      
>   }
> }
> ```

It's the last one. I tried in a empty scene too and worked. It gets the scene width and height to place the cards.
```js
  let centerX = Math.round(game.scenes.active.data.width/3);
  let centerY = Math.round(game.scenes.active.data.height/2);
```
I need to reproduce the bug to fix. 
1. Can you share your foundry version?
2. Can you share your swade version?
3. Settings in the scene?
4. Console log


![image](https://user-images.githubusercontent.com/4999783/120908269-bca2f400-c63e-11eb-99cf-dee2ca785b9d.png)

**Comment by kristianserrano** [comment]
- Foundry: v0.8.6
- SWADE: running the current develop branch that adds some new features for the Combat Tracker I've been working on.
- Settings in the scene (TXT file of the JSON export; GitHub doesn't accept JSON files for whatever dumb reason):
 [fvtt-Scene-landing-screen.txt](https://github.com/brunocalado/swademacros/files/6603519/fvtt-Scene-landing-screen.txt)
- Console log:
[immaterialplane.forge-vtt.com-1622945851731.log](https://github.com/brunocalado/swademacros/files/6603523/immaterialplane.forge-vtt.com-1622945851731.log)

**Comment by kristianserrano** [comment]
I created an empty scene with defaults, and this is where it placed it.
![Screen Shot 2021-06-05 at 10 20 47 PM](https://user-images.githubusercontent.com/1796189/120910363-4b6a3d80-c64c-11eb-9fad-4b4f412d6873.png)

I think if a scene is too small, it doesn't place it well.

**Comment by brunocalado** [comment]
> I created an empty scene with defaults, and this is where it placed it.
> ![Screen Shot 2021-06-05 at 10 20 47 PM](https://user-images.githubusercontent.com/1796189/120910363-4b6a3d80-c64c-11eb-9fad-4b4f412d6873.png)
> 
> I think if a scene is too small, it doesn't place it well.

I'll study a new way of placement.

Do you have a suggestion?

**Comment by kristianserrano** [comment]
Might need to do some math.

Something like size of cards + spacing between + # of rows/columns to determine the layout area. Then get the difference between that and the scene, then position it half that difference.

**Comment by kristianserrano** [comment]
Try this:

```js
const version = "v1.3";

/* Chase
Features
- Draw n cards placing them in the scene
- This macro can reset the table preventing from the error
- This macro can line up the cards
source:
icon: icons/sundries/gaming/playing-cards.webp
*/

async function makeTiles(html) {
    let spacingX = parseInt(html.find("#spacing-x")[0].value);
    let spacingY = parseInt(html.find("#spacing-y")[0].value);
    let rows = parseInt(html.find("#card-rows")[0].value);
    let columns = parseInt(html.find("#card-columns")[0].value);
    let resetTable = html.find("#reset")[0].value;
    const stackCards = html.find("#stack-cards")[0].checked;
    let tableName = html.find("#table-name")[0].value;
    let cardsToDraw = rows * columns;
    let cardHeight = parseInt(html.find("#card-height")[0].value);
    let cardWidth = parseInt(html.find("#card-width")[0].value);

    if (resetTable == "on") {
        await game.tables.find((el) => el.data.name == tableName).reset();
    }

    let cardDraws = (
        await game.tables
            .find((el) => el.data.name == tableName)
            .drawMany(cardsToDraw)
    ).results;

    const sceneWidth = canvas.scene.dimensions.sceneWidth;
    const sceneHeight = canvas.scene.dimensions.sceneHeight;
    const sceneRectX = canvas.scene.dimensions.sceneRect.x;
    const sceneRectY = canvas.scene.dimensions.sceneRect.y;

    let totalSpacingX = (spacingX * columns) - 1;
    let totalSpacingY = (spacingY * rows) - 1;
    let fullSpreadWidth = (cardWidth * columns) + totalSpacingX;
    let fullSpreadHeight = (cardHeight * rows) + totalSpacingY;

    if (fullSpreadWidth > sceneWidth || fullSpreadHeight > sceneHeight) {
        let newSpreadRatio = 1;

        if (fullSpreadWidth > sceneWidth) {
            newSpreadRatio = sceneWidth / fullSpreadWidth;
            cardWidth = cardWidth * newSpreadRatio;
            cardHeight = cardHeight * newSpreadRatio;
            spacingX = spacingX * newSpreadRatio;
            spacingY = spacingY * newSpreadRatio;
            totalSpacingX = (spacingX * columns) - 1;
            totalSpacingY = (spacingY * rows) - 1;
            fullSpreadWidth = cardWidth * columns + totalSpacingX;
            fullSpreadHeight = cardHeight * rows + totalSpacingY;
        }

        if (fullSpreadHeight > sceneHeight) {
            newSpreadRatio = sceneHeight / fullSpreadHeight;
            cardWidth = cardWidth * newSpreadRatio;
            cardHeight = cardHeight * newSpreadRatio;
            spacingX = spacingX * newSpreadRatio;
            spacingY = spacingY * newSpreadRatio;
            totalSpacingX = (spacingX * columns) - 1;
            totalSpacingY = (spacingY * rows) - 1;
            fullSpreadWidth = cardWidth * columns + totalSpacingX;
            fullSpreadHeight = cardHeight * rows + totalSpacingY;
        }
    }

    let startX = sceneRectX + ((sceneWidth - fullSpreadWidth) / 2);
    let startY = sceneRectY + ((sceneHeight - fullSpreadHeight) / 2);

    if (stackCards) {
        startX = sceneRectX + ((sceneWidth - cardWidth) / 2);
        startY = sceneRectY + ((sceneHeight - cardHeight) / 2);
    }

    let positionY = startY;
    let positionX = startX;
    let counter = 0;

    let tData;
    for (let y = 0; y < rows; y++) {
        for (let x = 0; x < columns; x++) {
            tData = {
                img: cardDraws[counter].data.img,
                width: cardWidth,
                height: cardHeight,
                x: positionX,
                y: positionY,
            };
            if (!stackCards) {
                positionX = positionX + cardWidth + spacingX;
            }
            await TileDocument.create(tData, { parent: canvas.scene });
            counter++;
        }
        if (!stackCards) {
            positionY = positionY + cardHeight + spacingY;
        }
        positionX = startX;
    }
}

function main() {
    //How Many Cards to Draw
    //Width/Height
    //Which Table to Draw From
    let cardsList = "";
    Array.from(game.tables).map((el) => {
        cardsList += `<option value="${el.data.name}">${el.data.name}</option>`;
    });

    let template = `
        <style scoped>
            .custom-sizing-spacing {
                margin-bottom: 1em;
            }
        </style>
        <form>
            <fieldset>
                <legend>Choose a Roll Table</legend>
                <p>
                    <label for="table-name">Table to Draw From: <select id="table-name">${cardsList}</select></label>
                </p>
                <p>
                    <label for="reset"><input type="checkbox" id="reset" checked/> Reset Table</label>
                </p>
            </fieldset>
            <fieldset>
                <legend>Layout</legend>
                <p>
                    <label for="card-rows">Rows: <input id="card-rows" type="number" min="1" style="width: 50px;" value=1></label>
                </p>
                <p>
                    <label for="card-columns">Columns: <input id="card-columns" type="number" min="1" style="width: 50px;" value=9></label>
                </p>
                <p>--OR--</p>
                <p>
                    <label for="stack-cards"><input type="checkbox" id="stack-cards"/> Stack cards into single pile</label>
                </p>
            </fieldset>
            <details class="custom-sizing-spacing">
                <summary>Customize Card Size and Spacing</summary>
                <fieldset>
                    <legend>Card Size (in pixels)</legend>
                    <p>
                        <label for="card-height">Height:
                            <input id="card-height" type="number" min="1" style="width: 50px;" value=150>
                        </label>
                    <p>
                        <label for="card-width">Width:
                            <input id="card-width" type="number" min="1" style="width: 50px;" value=107>
                        </label>
                    </p>
                </fieldset>
                <fieldset>
                    <legend>Spacing between Cards (in pixels)</legend>
                    <p>
                        <label for="spacing-x">Columns
                            <input id="spacing-x" type="number" min="0" max="100" value="10" step="1" style="width: 50px;">
                        </label>
                    </p>
                    <p>
                        <label for="spacing-y">Rows:
                            <input id="spacing-y" type="number" min="0" max="100" value="10" step="1" style="width: 50px;">
                        </label>
                    </p>
                </fieldset>
            </details>
        </form>
        `;
    new Dialog({
        title: `Draw Cards To Table - ${version}`,
        content: template,
        buttons: {
            ok: {
                label: "Draw",
                callback: async (html) => {
                    makeTiles(html);
                },
            },
            cancel: {
                label: "Cancel",
            },
        },
    }).render(true);
}

main();
```

**Comment by kristianserrano** [comment]
Making some corrections to the above. I forgot to account for padding around the scene.

**Comment by kristianserrano** [comment]
I've updated the macro in the previous comment. Give it a whirl.

**Comment by brunocalado** [comment]
Much much better.

I did not forget. I just couldn't study it.

Thank you very much. I'll upload this one.

**Comment by kristianserrano** [comment]
Minor detail, I'm not sure why the cards are output to the chat other than that's the default behavior, but if you wanted to turn that off, change the call to `.drawMany(cardsToDraw)` to `.drawMany(cardsToDraw, {displayChat: false})`.

**Comment by brunocalado** [comment]
Thank you very much. 

I'll add this option in the future.
