### ISSUE TITLE
Support Macro Only using Unskilled for the roll

### ISSUE THREAD

**Issue by thorgibrewer** [brunocalado/swademacros#11]
when executing it will properly pull up a window and the dropdown pulls all of the active token's skills, however, no matter which skill is selected the roll formula always references unskilled (maybe cause it is the first in the dropdown?) and populates the 1d4 and the -2 unskilled modifier. Chat card outputs results right (crit fail, fail, success and raise).

So, error seems to be the dropdown actually updating the roll formula away from the 1d4x[unskilled]

**Comment by brunocalado** [comment]
fixed
