### ISSUE TITLE
Dramastic Tasks with Challenge Tracker

### ISSUE THREAD

**Issue by Arnok13** [brunocalado/swademacros#15]
Hi,
when i use the Dramatic Task macro with Challenge Tracker wether it not display anything (empty tracker) or the deezfault tracker (0/4 and 0/3), compex and difficult are no longer implemented it seems.

**Comment by brunocalado** [comment]
Yes. I'll try to fix this today. 

The  Challenge Tracker update broke the macro. I found out on my wednesday game

**Comment by brunocalado** [comment]
> Yes. I'll try to fix this today.
> 
> The Challenge Tracker update broke the macro. I found out on my wednesday game

Enable color picker module. It'll work again.

**Comment by Arnok13** [comment]
![image](https://user-images.githubusercontent.com/4520046/189497347-b81388af-0d05-49bc-bd06-d7e0674a672f.png)

**Comment by brunocalado** [comment]
WTF I'll check it out

**Comment by brunocalado** [comment]
> ![image](https://user-images.githubusercontent.com/4520046/189497347-b81388af-0d05-49bc-bd06-d7e0674a672f.png)

Fixed. Update

**Comment by Arnok13** [comment]
Perfect ! 
![image](https://user-images.githubusercontent.com/4520046/189522672-de8ab117-7520-4988-a23e-38d576746075.png)
thanks a lot.
