### ISSUE TITLE
Unshaken Macro Generates an Error in Console

### ISSUE THREAD

**Issue by sanjo1991** [brunocalado/swademacros#2]
Execution of "Unshaken" Macros resolves to:
SyntaxError: redeclaration of formal parameter token

**Comment by brunocalado** [comment]
I'll check it out.

**Comment by brunocalado** [comment]
I just tested. Worked fine.

Can you give me your build? Foundry, swade version, actor

**Comment by sanjo1991** [comment]
Hi, i'm using Foundry 0.8.6, SWADE 0.19.3, Actor Wildcards and Extras with same syntax error. Using Forge. However in a new game it is working. I will investigate what caused troubles.

**Comment by sanjo1991** [comment]
It seems that the module "Advanced Macros" which is a prerequisite for "The furnance" causes the error.

**Comment by sanjo1991** [comment]
However i dont really need the "Advanced Macros" at the moment, so i just disabled them. Thanks for your patience!
