### ISSUE TITLE
Arcane Devices

### ISSUE THREAD

**Issue by JusticeTheAwesome** [brunocalado/swademacros#3]
Hi!, We love your macros, and we use them a lot!. Thank you for your work enhancing a great system such as SWADE.

That being said, I've got a request. It had been recently added the Arcane Device option to the Items in SWADE. I was wondering if it is any way to add it to the attack macro. Because it doesn't seem to work. When I use the Attack Macro, the "activate device" option doesn't show up. 

Once again, thank you for your time.

**Comment by brunocalado** [comment]
Hi.

I'm lost. What attack macro? I don't have it. Are you sure it's a macro from here?

**Comment by Alis-72** [comment]
perhaps  'Attack Macro' in question is the one in  SWADE Tools module? https://github.com/lipefl/swade-tools


> Hi!, We love your macros, and we use them a lot!. Thank you for your work enhancing a great system such as SWADE.
> 
> That being said, I've got a request. It had been recently added the Arcane Device option to the Items in SWADE. I was wondering if it is any way to add it to the attack macro. Because it doesn't seem to work. When I use the Attack Macro, the "activate device" option doesn't show up.
> 
> Once again, thank you for your time.
