### ISSUE TITLE
Adventure Card Macro is not putting adventure cards in items

### ISSUE THREAD

**Issue by gravagehulk** [brunocalado/swademacros#4]
I have everything set up, including the Adventure Card table. Running the macro, it says it put 3 cards in the player's gear, but when I check, there's nothing there.

![image](https://user-images.githubusercontent.com/69117052/145464992-5bf0a6b3-cc5f-4382-bf34-7be0171eb9b6.png)

**Comment by brunocalado** [comment]
I'll check. 

Is it worked before?
Can you check the console for errors?

**Comment by gravagehulk** [comment]
I honestly never tried to use it until now. Let me check the console and I'll post anything that shows up.

**Comment by gravagehulk** [comment]
It looks like it THINKS it's creating them, but I'm still not seeing anything on the actual character sheet. 

![image](https://user-images.githubusercontent.com/69117052/145466003-2bf865f5-a678-40c7-9b44-71122949b5b9.png)

**Comment by gravagehulk** [comment]
Wait. Scratch that. I had to open the character sheet from the actor directory instead of the token. Not sure what's going on there. Apologies. It is working!

**Comment by brunocalado** [comment]
> Wait. Scratch that. I had to open the character sheet from the actor directory instead of the token. Not sure what's going on there. Apologies. It is working!

Oh, I know. The token should be linked. Was it unlinked?

**Comment by gravagehulk** [comment]
I don't think so. It's weird. I'll do some more testing on my end. Your macro looks like it's working normally, though. Sorry for the trouble.

**Comment by brunocalado** [comment]
It's ok.
