### ISSUE TITLE
Healing Macro is not working

### ISSUE THREAD

**Issue by gravagehulk** [brunocalado/swademacros#6]
Foundry 9, version 242
SWADE 0.22.5

The Healing macro stopped working recently. I'm not sure what changed. It was working for me about a week ago. Here is the console error. It's something about the dialog button:

![image](https://user-images.githubusercontent.com/69117052/149571396-9c23715c-7afd-417b-a3ef-2f9799a0b657.png)

**Comment by brunocalado** [comment]
Are you using advanced macros module? It breaks things.

I tested and the vigor roll worked. Trying to find out.

**Comment by gravagehulk** [comment]
I am using Advanced Macros. I didn't even realize it was enabled. Is that required by SWIM or something? I don't think I enabled that one manually. I just disabled it and that seems to have fixed the problem. Thanks!

**Comment by brunocalado** [comment]
I think I found out the bug. I'll patch up soon.

**Comment by gravagehulk** [comment]
You're the man! Thank you.

**Comment by brunocalado** [comment]
fixed
