### ISSUE TITLE
Request: Additional options to Active Effect Builder & Boost/Lower trait macro

### ISSUE THREAD

**Issue by Alis-72** [brunocalado/swademacros#7]
Now that SWADE supports Active Effect durations, it would be awesome to have added option on said macros to have duration set to 5 and expiration 'end of turn prompt'+loose on hold checked.
That could be simple checkbox as those expiration options are same in all powers with duration.

**Comment by grendel111111** [comment]
And also if possible a warning when used as lower. (Like the warning they get for stunned with a remove or keep dialog box.

**Comment by brunocalado** [comment]
I'll take a look

**Comment by brunocalado** [comment]
> Now that SWADE supports Active Effect durations, it would be awesome to have added option on said macros to have duration set to 5 and expiration 'end of turn prompt'+loose on hold checked. That could be simple checkbox as those expiration options are same in all powers with duration.

done

**Comment by brunocalado** [comment]
> And also if possible a warning when used as lower. (Like the warning they get for stunned with a remove or keep dialog box.

There is a chat message:
![image](https://user-images.githubusercontent.com/4999783/155859829-44829e3f-272a-416b-8d73-a3c7fee4f8f8.png)

**Comment by grendel111111** [comment]
You have set lower to run for 5 rounds and warn to expire after the 5 rounds like the raise, but lower doesn't have an expire, but you need the option to remove every turn, you make a free reroll to remove at the start of each round.
![image](https://user-images.githubusercontent.com/80164119/155867260-9a59cbf0-0f80-47aa-bb82-44d0b9dcf877.png)

If you don't put the 5 in rounds in when making it lower, it will give this warning every round.
![image](https://user-images.githubusercontent.com/80164119/155867397-245a73d8-68cf-4399-a609-5f279e721023.png)

**Comment by brunocalado** [comment]
Test now.

**Comment by grendel111111** [comment]
It's good. For some reason between 1.3 and 1.4 when you select lower it is adding the effect to the character, but the icon is no longer showing token. (It still does for raise)

**Comment by brunocalado** [comment]
> din

I don't know too.

https://user-images.githubusercontent.com/4999783/155985272-9526918a-8f5b-411c-841e-8c60cbdee551.mp4

**Comment by brunocalado** [comment]
thatlonelybugbear: So a guess would be that one effect is Passive and the other Temporary, so the passive might not show that on the actor. I can see duration 0 and 5, so the passive will not be shown 🤷‍♂️

**Comment by grendel111111** [comment]
Sorry I am still new to macros. the change happened between 1.3 when it was showing the icon and the 1.4 where it stopped.  I think the only change was to do with the expire. If you set any duration to 0 it disappears.
Sorry just saw your comment.

**Comment by grendel111111** [comment]
Would setting it to be duration 1 notify at end of round work?

**Comment by brunocalado** [comment]
> Would setting it to be duration 1 notify at end of round work?

Yes. But, is this the best solution?

https://gitlab.com/peginc/swade/-/issues/467

**Comment by grendel111111** [comment]
Purely guessing. This is well out of my depth.

**Comment by brunocalado** [comment]
> Would setting it to be duration 1 notify at end of round work?

Done.

**Comment by brunocalado** [comment]
Done. To change to 0 we need a change in the system.
