### ISSUE TITLE
Request: Configuration for "Auto Update" macro managers

### ISSUE THREAD

**Issue by WasabiBurns** [brunocalado/swademacros#8]
For the "Auto Update" versions of the macro managers, include a way to configure the list of macros included with each one. To configure the list you currently need to pull in the macro from the non-auto update compendium.

**Comment by brunocalado** [comment]
> For the "Auto Update" versions of the macro managers, include a way to configure the list of macros included with each one. To configure the list you currently need to pull in the macro from the non-auto update compendium.

Did you check the docs?
![image](https://user-images.githubusercontent.com/4999783/155859887-6c009bd6-0ea6-4e35-81f1-59cb08121d9e.png)
