### ISSUE TITLE
Imcompatibilities with "Swade tools"

### ISSUE THREAD

**Issue by Lifthraser** [brunocalado/swademacros#9]
Some macros from the module "macros for swade" dont work anymore with swade tools activated.
Exemple macros that dont work: "Test" and "Support"
The macros works again when i disable swade tools.
Posting this on both git.

**Comment by Lifthraser** [comment]
Link on the issue on the other side: https://github.com/lipefl/swade-tools/issues/110

**Comment by brunocalado** [comment]
swade tools override some systems functions, I would have to study the module. MAybe libwrapper could solve that.

**Comment by lipefl** [comment]
I made a pull request to solve the problem. Thanks!

**Comment by brunocalado** [comment]
merged
